### ISSUE TITLE
Enhancement: Enable Discussions

### ISSUE THREAD

**Issue by cassiofb-dev** [HyunCafe/contribute-practice#24]
Hello HyunCafe!

There's a cool feature on github called discussions. It's like a forum for the repository, there we can ask, share things and chat with each other.

[Check here how to setup it](https://docs.github.com/en/discussions/quickstart)!

Happy coding!

<img alt='separator' src='https://raw.githubusercontent.com/HyunCafe/contribute-practice/main/assests/borderseperator.gif'/>

<p align='center'>
  <img alt='coffee coding' src='https://media.tenor.com/Lzr7afFB7xUAAAAM/microsoft-hackathon-hackathon.gif'/>
</p>

**Comment by HyunCafe** [comment]
Cool! Thanks, I set it up!

**Comment by cassiofb-dev** [comment]
Awesome, I'm closing this issue and will check it out!
